language: node_js
node_js:
  - 6.9.2
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
before_install:
  - npm install
addons:
  firefox: "50.0"
script:
  - npm run travis
